# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2020, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 1.0.2 on 2020-05-07 23:37:52.

require 'ads_common/savon_service'
require 'ad_manager_api/v202005/stream_activity_monitor_service_registry'

module AdManagerApi; module V202005; module StreamActivityMonitorService
  class StreamActivityMonitorService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v202005'
      super(config, endpoint, namespace, :v202005)
    end

    def get_sam_sessions_by_statement(*args, &block)
      return execute_action('get_sam_sessions_by_statement', args, &block)
    end

    def get_sam_sessions_by_statement_to_xml(*args)
      return get_soap_xml('get_sam_sessions_by_statement', args)
    end

    def register_sessions_for_monitoring(*args, &block)
      return execute_action('register_sessions_for_monitoring', args, &block)
    end

    def register_sessions_for_monitoring_to_xml(*args)
      return get_soap_xml('register_sessions_for_monitoring', args)
    end

    private

    def get_service_registry()
      return StreamActivityMonitorServiceRegistry
    end

    def get_module()
      return AdManagerApi::V202005::StreamActivityMonitorService
    end
  end
end; end; end
