#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.6.0 on 2011-12-02 16:40:55.

require 'ads_common/savon_service'
require 'adwords_api/v201008/bid_landscape_service_registry'

module AdwordsApi; module V201008; module BidLandscapeService
  class BidLandscapeService < AdsCommon::SavonService
    def initialize(api, endpoint)
      namespace = 'https://adwords.google.com/api/adwords/cm/v201008'
      super(api, endpoint, namespace, :v201008)
    end

    def get_bid_landscape(*args, &block)
      return execute_action('get_bid_landscape', args, &block)
    end

    private

    def get_service_registry()
      return BidLandscapeServiceRegistry
    end

    def get_module()
      return AdwordsApi::V201008::BidLandscapeService
    end
  end
end; end; end
