# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2012, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.2 on 2013-07-10 22:03:06.

require 'ads_common/savon_service'
require 'adwords_api/v201306/ad_group_service_registry'

module AdwordsApi; module V201306; module AdGroupService
  class AdGroupService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://adwords.google.com/api/adwords/cm/v201306'
      super(config, endpoint, namespace, :v201306)
    end

    def get(*args, &block)
      return execute_action('get', args, &block)
    end

    def mutate(*args, &block)
      return execute_action('mutate', args, &block)
    end

    def query(*args, &block)
      return execute_action('query', args, &block)
    end

    private

    def get_service_registry()
      return AdGroupServiceRegistry
    end

    def get_module()
      return AdwordsApi::V201306::AdGroupService
    end
  end
end; end; end
