#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.5.0 on 2011-08-02 15:33:04.

require 'ads_common/savon_service'
require 'dfp_api/v201101/network_service_registry'

module DfpApi; module V201101; module NetworkService
  class NetworkService < AdsCommon::SavonService
    def initialize(api, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201101'
      super(api, endpoint, namespace, :v201101)
    end

    def get_current_network(*args)
      return execute_action('get_current_network', args)
    end

    def update_network(*args)
      return execute_action('update_network', args)
    end

    def get_all_networks(*args)
      return execute_action('get_all_networks', args)
    end

    private

    def get_service_registry()
      return NetworkServiceRegistry
    end

    def get_module()
      return DfpApi::V201101::NetworkService
    end
  end
end; end; end
