#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.5.3 on 2011-10-24 17:27:02.

require 'ads_common/savon_service'
require 'dfp_api/v201108/company_service_registry'

module DfpApi; module V201108; module CompanyService
  class CompanyService < AdsCommon::SavonService
    def initialize(api, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201108'
      super(api, endpoint, namespace, :v201108)
    end

    def update_company(*args, &block)
      return execute_action('update_company', args, &block)
    end

    def create_companies(*args, &block)
      return execute_action('create_companies', args, &block)
    end

    def create_company(*args, &block)
      return execute_action('create_company', args, &block)
    end

    def get_companies_by_statement(*args, &block)
      return execute_action('get_companies_by_statement', args, &block)
    end

    def get_company(*args, &block)
      return execute_action('get_company', args, &block)
    end

    def update_companies(*args, &block)
      return execute_action('update_companies', args, &block)
    end

    private

    def get_service_registry()
      return CompanyServiceRegistry
    end

    def get_module()
      return DfpApi::V201108::CompanyService
    end
  end
end; end; end
