# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2016, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.12.3 on 2016-08-09 15:51:03.

require 'ads_common/savon_service'
require 'dfp_api/v201605/line_item_service_registry'

module DfpApi; module V201605; module LineItemService
  class LineItemService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201605'
      super(config, endpoint, namespace, :v201605)
    end

    def create_line_items(*args, &block)
      return execute_action('create_line_items', args, &block)
    end

    def create_line_items_to_xml(*args)
      return get_soap_xml('create_line_items', args)
    end

    def get_line_items_by_statement(*args, &block)
      return execute_action('get_line_items_by_statement', args, &block)
    end

    def get_line_items_by_statement_to_xml(*args)
      return get_soap_xml('get_line_items_by_statement', args)
    end

    def perform_line_item_action(*args, &block)
      return execute_action('perform_line_item_action', args, &block)
    end

    def perform_line_item_action_to_xml(*args)
      return get_soap_xml('perform_line_item_action', args)
    end

    def update_line_items(*args, &block)
      return execute_action('update_line_items', args, &block)
    end

    def update_line_items_to_xml(*args)
      return get_soap_xml('update_line_items', args)
    end

    private

    def get_service_registry()
      return LineItemServiceRegistry
    end

    def get_module()
      return DfpApi::V201605::LineItemService
    end
  end
end; end; end
