# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2012, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.8.0 on 2012-08-21 13:57:36.

require 'ads_common/savon_service'
require 'dfp_api/v201203/company_service_registry'

module DfpApi; module V201203; module CompanyService
  class CompanyService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201203'
      super(config, endpoint, namespace, :v201203)
    end

    def create_companies(*args, &block)
      return execute_action('create_companies', args, &block)
    end

    def create_company(*args, &block)
      return execute_action('create_company', args, &block)
    end

    def get_companies_by_statement(*args, &block)
      return execute_action('get_companies_by_statement', args, &block)
    end

    def get_company(*args, &block)
      return execute_action('get_company', args, &block)
    end

    def update_companies(*args, &block)
      return execute_action('update_companies', args, &block)
    end

    def update_company(*args, &block)
      return execute_action('update_company', args, &block)
    end

    private

    def get_service_registry()
      return CompanyServiceRegistry
    end

    def get_module()
      return DfpApi::V201203::CompanyService
    end
  end
end; end; end
