# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.8 on 2015-03-12 10:31:32.

require 'ads_common/savon_service'
require 'adwords_api/v201502/media_service_registry'

module AdwordsApi; module V201502; module MediaService
  class MediaService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://adwords.google.com/api/adwords/cm/v201502'
      super(config, endpoint, namespace, :v201502)
    end

    def get(*args, &block)
      return execute_action('get', args, &block)
    end

    def query(*args, &block)
      return execute_action('query', args, &block)
    end

    def upload(*args, &block)
      return execute_action('upload', args, &block)
    end

    private

    def get_service_registry()
      return MediaServiceRegistry
    end

    def get_module()
      return AdwordsApi::V201502::MediaService
    end
  end
end; end; end
