# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.6 on 2014-08-12 14:22:33.

require 'ads_common/savon_service'
require 'dfp_api/v201405/content_bundle_service_registry'

module DfpApi; module V201405; module ContentBundleService
  class ContentBundleService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201405'
      super(config, endpoint, namespace, :v201405)
    end

    def create_content_bundles(*args, &block)
      return execute_action('create_content_bundles', args, &block)
    end

    def get_content_bundles_by_statement(*args, &block)
      return execute_action('get_content_bundles_by_statement', args, &block)
    end

    def perform_content_bundle_action(*args, &block)
      return execute_action('perform_content_bundle_action', args, &block)
    end

    def update_content_bundles(*args, &block)
      return execute_action('update_content_bundles', args, &block)
    end

    private

    def get_service_registry()
      return ContentBundleServiceRegistry
    end

    def get_module()
      return DfpApi::V201405::ContentBundleService
    end
  end
end; end; end
