source 'http://rubygems.org'

gem 'rails', '3.2.5'
gem 'jquery-rails'

# Using sqlite by default.
gem 'sqlite3'

# AdWords API gem.
gem 'google-adwords-api'

# Gem for OAuth authorization.
gem 'oauth'
