# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2023, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 1.0.3 on 2023-05-23 14:35:41.

require 'ads_common/savon_service'
require 'ad_manager_api/v202211/label_service_registry'

module AdManagerApi; module V202211; module LabelService
  class LabelService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v202211'
      super(config, endpoint, namespace, :v202211)
    end

    def create_labels(*args, &block)
      return execute_action('create_labels', args, &block)
    end

    def create_labels_to_xml(*args)
      return get_soap_xml('create_labels', args)
    end

    def get_labels_by_statement(*args, &block)
      return execute_action('get_labels_by_statement', args, &block)
    end

    def get_labels_by_statement_to_xml(*args)
      return get_soap_xml('get_labels_by_statement', args)
    end

    def perform_label_action(*args, &block)
      return execute_action('perform_label_action', args, &block)
    end

    def perform_label_action_to_xml(*args)
      return get_soap_xml('perform_label_action', args)
    end

    def update_labels(*args, &block)
      return execute_action('update_labels', args, &block)
    end

    def update_labels_to_xml(*args)
      return get_soap_xml('update_labels', args)
    end

    private

    def get_service_registry()
      return LabelServiceRegistry
    end

    def get_module()
      return AdManagerApi::V202211::LabelService
    end
  end
end; end; end
