#!/usr/bin/ruby
#
# Authors:: api.dklimkin@gmail.com (Danial Klimkin)
#
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
#
# License:: Licensed under the Apache License, Version 2.0 (the "License");
#           you may not use this file except in compliance with the License.
#           You may obtain a copy of the License at
#
#           http://www.apache.org/licenses/LICENSE-2.0
#
#           Unless required by applicable law or agreed to in writing, software
#           distributed under the License is distributed on an "AS IS" BASIS,
#           WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#           implied.
#           See the License for the specific language governing permissions and
#           limitations under the License.
#
# DoubleClick Ad Exchange Buyer API Rakefile
#

require 'rubygems'
require 'rake/gempackagetask'

files = FileList["{examples}/**/*", "Rakefile"].to_a
docs = ['README', 'COPYING', 'ChangeLog']

spec = Gem::Specification.new do |s|
  s.name = 'google-adx-buyer-api'
  s.version = '0.2.0'
  s.author = 'Danial Klimkin'
  s.email = 'api.dklimkin@gmail.com'
  s.homepage = 'http://code.google.com/p/google-api-ads-ruby/'
  s.platform = Gem::Platform::RUBY
  s.summary = 'Ruby Client libraries for DoubleClick Ad Exchange Buyer API'
  s.description = ("%s is a DoubleClick Ad Exchange API Buyer API client " +
      "library for Ruby") % s.name
  s.files = files
  s.has_rdoc = true
  s.extra_rdoc_files = docs
  s.add_dependency('google-adwords-api', '~> 0.1.2')
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

desc 'Default target - package'
task :default => :package
