#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.3.1 on 2011-06-10 21:51:52.

module DfpApi; module V201103; module PublisherQueryLanguageService
  class PublisherQueryLanguageServiceRegistry
    PUBLISHERQUERYLANGUAGESERVICE_METHODS = {:select=>{:output=>{:name=>"select_response", :fields=>[{:type=>"ResultSet", :max_occurs=>1, :name=>:rval, :min_occurs=>0}]}, :input=>[{:type=>"Statement", :max_occurs=>1, :name=>:select_statement, :min_occurs=>0}]}}
    PUBLISHERQUERYLANGUAGESERVICE_TYPES = {:TextValue=>{:base=>"Value", :fields=>[{:type=>"string", :max_occurs=>1, :name=>:value, :min_occurs=>0}]}, :Row=>{:fields=>[{:type=>"Value", :max_occurs=>nil, :name=>:values, :min_occurs=>0}]}, :SoapResponseHeader=>{:fields=>[{:type=>"string", :max_occurs=>1, :name=>:request_id, :min_occurs=>0}, {:type=>"long", :max_occurs=>1, :name=>:response_time, :min_occurs=>0}]}, :Statement=>{:fields=>[{:type=>"string", :max_occurs=>1, :name=>:query, :min_occurs=>0}, {:type=>"String_ValueMapEntry", :max_occurs=>nil, :name=>:values, :min_occurs=>0}]}, :ResultSet=>{:fields=>[{:type=>"ColumnType", :max_occurs=>nil, :name=>:column_types, :min_occurs=>0}, {:type=>"Row", :max_occurs=>nil, :name=>:rows, :min_occurs=>0}]}, :Value=>{:abstract=>true, :fields=>[{:type=>"string", :max_occurs=>1, :name=>:value_type, :min_occurs=>0}]}, :String_ValueMapEntry=>{:fields=>[{:type=>"string", :max_occurs=>1, :name=>:key, :min_occurs=>0}, {:type=>"Value", :max_occurs=>1, :name=>:value, :min_occurs=>0}]}, :NumberValue=>{:base=>"Value", :fields=>[{:type=>"string", :max_occurs=>1, :name=>:value, :min_occurs=>0}]}, :Authentication=>{:abstract=>true, :fields=>[{:type=>"string", :max_occurs=>1, :name=>:authentication_type, :min_occurs=>0}]}, :BooleanValue=>{:base=>"Value", :fields=>[{:type=>"boolean", :max_occurs=>1, :name=>:value, :min_occurs=>0}]}, :SoapRequestHeader=>{:fields=>[{:type=>"string", :max_occurs=>1, :name=>:network_code, :min_occurs=>0}, {:type=>"string", :max_occurs=>1, :name=>:application_name, :min_occurs=>0}, {:type=>"Authentication", :max_occurs=>1, :name=>:authentication, :min_occurs=>0}]}, :OAuth=>{:base=>"Authentication", :fields=>[{:type=>"string", :max_occurs=>1, :name=>:parameters, :min_occurs=>0}]}, :ColumnType=>{:fields=>[{:type=>"string", :max_occurs=>1, :name=>:label_name, :min_occurs=>0}]}, :ClientLogin=>{:base=>"Authentication", :fields=>[{:type=>"string", :max_occurs=>1, :name=>:token, :min_occurs=>0}]}}

    def self.get_method_signature(method_name)
      return PUBLISHERQUERYLANGUAGESERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return PUBLISHERQUERYLANGUAGESERVICE_TYPES[type_name.to_sym]
    end
  end

  # Base class for exceptions.
  class ApplicationException < DfpApi::Errors::ApiException
    attr_reader :message  # string
    attr_reader :application_exception_type  # string
  end

  # Exception class for holding a list of service errors.
  class ApiException < ApplicationException
    attr_reader :errors  # ApiError
    def initialize(exception_fault)
      @array_fields = [] if !defined?(@array_fields)
      @array_fields << 'errors'
      super(exception_fault)
    end
  end
end; end; end
