# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.5 on 2013-11-25 14:25:11.

require 'ads_common/savon_service'
require 'dfp_api/v201311/creative_wrapper_service_registry'

module DfpApi; module V201311; module CreativeWrapperService
  class CreativeWrapperService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201311'
      super(config, endpoint, namespace, :v201311)
    end

    def create_creative_wrapper(*args, &block)
      return execute_action('create_creative_wrapper', args, &block)
    end

    def create_creative_wrappers(*args, &block)
      return execute_action('create_creative_wrappers', args, &block)
    end

    def get_creative_wrapper(*args, &block)
      return execute_action('get_creative_wrapper', args, &block)
    end

    def get_creative_wrappers_by_statement(*args, &block)
      return execute_action('get_creative_wrappers_by_statement', args, &block)
    end

    def perform_creative_wrapper_action(*args, &block)
      return execute_action('perform_creative_wrapper_action', args, &block)
    end

    def update_creative_wrapper(*args, &block)
      return execute_action('update_creative_wrapper', args, &block)
    end

    def update_creative_wrappers(*args, &block)
      return execute_action('update_creative_wrappers', args, &block)
    end

    private

    def get_service_registry()
      return CreativeWrapperServiceRegistry
    end

    def get_module()
      return DfpApi::V201311::CreativeWrapperService
    end
  end
end; end; end
