#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.5.1 on 2011-09-21 12:00:47.

require 'ads_common/savon_service'
require 'adwords_api/v13/account_service_registry'

module AdwordsApi; module V13; module AccountService
  class AccountService < AdsCommon::SavonService
    def initialize(api, endpoint)
      namespace = 'https://adwords.google.com/api/adwords/v13'
      super(api, endpoint, namespace, :v13)
    end

    def update_account_info(*args)
      return execute_action('update_account_info', args)
    end

    def get_account_info(*args)
      return execute_action('get_account_info', args)
    end

    def get_client_account_infos(*args)
      return execute_action('get_client_account_infos', args)
    end

    def get_client_accounts(*args)
      return execute_action('get_client_accounts', args)
    end

    def get_mcc_alerts(*args)
      return execute_action('get_mcc_alerts', args)
    end

    private

    def get_service_registry()
      return AccountServiceRegistry
    end

    def get_module()
      return AdwordsApi::V13::AccountService
    end
  end
end; end; end
