#!/usr/bin/ruby
# This is auto-generated code, changes will be overwritten.
# Copyright:: Copyright 2011, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License,Version 2.0 (the "License").
#
# Code generated by AdsCommon library 0.5.2 on 2011-10-20 20:34:44.

require 'adwords_api/errors'

module AdwordsApi; module V13; module ReportService
  class ReportServiceRegistry
    REPORTSERVICE_METHODS = {:get_all_jobs=>{:input=>[], :output=>{:fields=>[{:type=>"ReportJob", :max_occurs=>:unbounded, :name=>:get_all_jobs_return}], :name=>"get_all_jobs_response"}}, :get_gzip_report_download_url=>{:input=>[{:type=>"long", :name=>:report_job_id}], :output=>{:fields=>[{:type=>"string", :name=>:get_gzip_report_download_url_return}], :name=>"get_gzip_report_download_url_response"}}, :schedule_report_job=>{:input=>[{:type=>"ReportJob", :name=>:job}], :output=>{:fields=>[{:type=>"long", :name=>:schedule_report_job_return}], :name=>"schedule_report_job_response"}}, :get_report_job_status=>{:input=>[{:type=>"long", :name=>:report_job_id}], :output=>{:fields=>[{:type=>"ReportJobStatus", :name=>:get_report_job_status_return}], :name=>"get_report_job_status_response"}}, :validate_report_job=>{:input=>[{:type=>"ReportJob", :name=>:job}], :output=>{:fields=>[], :name=>"validate_report_job_response"}}, :get_report_download_url=>{:input=>[{:type=>"long", :name=>:report_job_id}], :output=>{:fields=>[{:type=>"string", :name=>:get_report_download_url_return}], :name=>"get_report_download_url_response"}}, :delete_report=>{:input=>[{:type=>"long", :name=>:report_job_id}], :output=>{:fields=>[], :name=>"delete_report_response"}}}
    REPORTSERVICE_TYPES = {:DefinedReportJob=>{:fields=>[{:type=>"AdGroupStatus", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:ad_group_statuses}, {:type=>"long", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:ad_groups}, {:type=>"AdWordsType", :min_occurs=>0, :name=>:ad_words_type}, {:type=>"string", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:aggregation_types}, {:type=>"CampaignStatus", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:campaign_statuses}, {:type=>"int", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:campaigns}, {:type=>"boolean", :min_occurs=>0, :name=>:include_zero_impression}, {:type=>"KeywordStatus", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:keyword_statuses}, {:type=>"KeywordType", :min_occurs=>0, :name=>:keyword_type}, {:type=>"string", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:keywords}, {:type=>"string", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:selected_columns}, {:type=>"string", :name=>:selected_report_type}], :base=>"ReportJob"}, :ReportJob=>{:fields=>[{:type=>"string", :max_occurs=>:unbounded, :min_occurs=>0, :name=>:client_emails}, {:type=>"boolean", :min_occurs=>0, :name=>:cross_client}, {:type=>"date", :name=>:end_day}, {:type=>"long", :min_occurs=>0, :name=>:id}, {:type=>"string", :min_occurs=>0, :name=>:name}, {:type=>"date", :name=>:start_day}, {:type=>"ReportJobStatus", :min_occurs=>0, :name=>:status}], :abstract=>true}}
    REPORTSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return REPORTSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return REPORTSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return REPORTSERVICE_NAMESPACES[index]
    end
  end

  class ApiException < AdwordsApi::Errors::ApiException
    attr_reader :code  # int
    attr_reader :errors  # ApiError
    attr_reader :internal  # boolean
    attr_reader :message  # string
    attr_reader :trigger  # string
    def initialize(exception_fault)
      @array_fields ||= []
      @array_fields << 'errors'
      super(exception_fault)
    end
  end
end; end; end
