# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.3 on 2013-06-25 15:49:37.

require 'ads_common/savon_service'
require 'dfp_api/v201306/proposal_service_registry'

module DfpApi; module V201306; module ProposalService
  class ProposalService < AdsCommon::SavonService
    def initialize(config, endpoint)
      namespace = 'https://www.google.com/apis/ads/publisher/v201306'
      super(config, endpoint, namespace, :v201306)
    end

    def create_proposal(*args, &block)
      return execute_action('create_proposal', args, &block)
    end

    def create_proposals(*args, &block)
      return execute_action('create_proposals', args, &block)
    end

    def get_proposal(*args, &block)
      return execute_action('get_proposal', args, &block)
    end

    def get_proposals_by_statement(*args, &block)
      return execute_action('get_proposals_by_statement', args, &block)
    end

    def perform_proposal_action(*args, &block)
      return execute_action('perform_proposal_action', args, &block)
    end

    def update_proposal(*args, &block)
      return execute_action('update_proposal', args, &block)
    end

    def update_proposals(*args, &block)
      return execute_action('update_proposals', args, &block)
    end

    private

    def get_service_registry()
      return ProposalServiceRegistry
    end

    def get_module()
      return DfpApi::V201306::ProposalService
    end
  end
end; end; end
